version = 1

test_patterns = ["*/test/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  ecma_version = "2020"
  module_system = "commonjs"
  environment = [
    "nodejs",
    "jest"
  ]
  dialect = "typescript"
  style_guide = "airbnb"
  plugins = ["react"]
