version = 1

test_patterns = ["*/test/**"]

exclude_patterns = ["*/flow-typed/npm/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  ecma_version = "2020"
  module_system = "commonjs"
  environment = [
    "nodejs",
    "jest"
  ]
  plugins = ["react"]
  style_guide = "airbnb"
  dialect = "typescript"
